### ISSUE TITLE
build一直报错

### ISSUE THREAD

**Issue by fanlingyin** [renrenio/renren-fast-vue#89]
ERROR in ./src/assets/scss/index.scss
Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, scandir 'D:\code\perCode\renren-fast-vue\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:785:3)
    at Object.getInstalledBinaries (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\extensions.js:129:13)
    at foundBinariesList (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\code\perCode\renren-fast-vue\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by Bob4F** [comment]
me too

**Comment by Bob4F** [comment]
> ERROR in ./src/assets/scss/index.scss
> Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, scandir 'D:\code\perCode\renren-fast-vue\node_modules\node-sass\vendor'
> at Object.readdirSync (fs.js:785:3)
> at Object.getInstalledBinaries (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\extensions.js:129:13)
> at foundBinariesList (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\errors.js:20:15)
> at foundBinaries (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\errors.js:15:5)
> at Object.module.exports.missingBinary (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\errors.js:45:5)
> at module.exports (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\binding.js:15:30)
> at Object. (D:\code\perCode\renren-fast-vue\node_modules\node-sass\lib\index.js:14:35)
> at Module._compile (internal/modules/cjs/loader.js:701:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> at Module.load (internal/modules/cjs/loader.js:600:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (internal/modules/cjs/helpers.js:22:18)
> at Object. (D:\code\perCode\renren-fast-vue\node_modules\sass-loader\lib\loader.js:3:14)
> at Module._compile (internal/modules/cjs/loader.js:701:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> at Module.load (internal/modules/cjs/loader.js:600:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (internal/modules/cjs/helpers.js:22:18)

你可以把npm版本转为10.xx.x，最新的版本无法成功

**Comment by 472173958** [comment]
感觉一帮菜鸡提问

**Comment by fanlingyin** [comment]
> 感觉一帮菜鸡提问

你又很棒喽
